<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>My Sample Domain</title>
		<link href="/css/main.css" rel="stylesheet" type="text/css">	
		<script type="text/javascript" src="/js/jquery.min.js"></script>
		<?
		$this->include_css_files();
		$this->include_js_files();
		?>
	</head>

	<body>
		<?= $this->print_view(); ?>
	</body>
</html>
